### PR TITLE
Fix some messages & language-es file

### PR DESCRIPTION
**Pull request by xtomyserrax**
Dont merge this pull until I add the spanish file. While I was translating to spanish I found some small typos so well, ill be fixing them :)

### CODE REVIEW

**Comment by xtomyserrax** [comment]
Done with the spanish file :) ; If there are any errors let me know, I tried it in my server though

Also I saw this small placeholder not being replaced when rank doesnt exist: https://imgur.com/a/eBLRsqY

Thanks :D

**Comment by RoinujNosde** [comment]
Thanks!


> Also I saw this small placeholder not being replaced when rank doesnt exist: https://imgur.com/a/eBLRsqY

https://github.com/marcelo-mason/SimpleClans/blob/009564f732d5d248e35a4cdc38c9c3f95959be66/src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/RankCommand.java#L112
Forgot to format.

I'm almost finishing that language update.

**Comment by xtomyserrax** [comment]
Cool, will be a really amazing update. Also in my plugins I make a command to reset language files so owners dont really need to go to plugins files.

So for example /clan fixenglish would delete the language.yml file and generate a new one, so any new messages added in an update are there and no missing-language message is sent (idk if you find it useful or not)

**Comment by RoinujNosde** [comment]
> So for example /clan fixenglish would delete the language.yml file and generate a new one, so any new messages added in an update are there and no missing-language message is sent (idk if you find it useful or not)

The update will take care of this.
That message will only appear if the owner deletes the message inside the jar.

> And what do you think on ordering the /clan help page alphabetically? I may be able to help with that in another pull if you want (or this one)

I'm not sure.
Currently it's ordered by importance, right? /clan create is the first

**Comment by xtomyserrax** [comment]
Ohhh got it if its by importance, its right that way then

**Comment by xtomyserrax** [comment]
Finished with capitalized lol

**Comment by RoinujNosde** [comment]
Thank you again!

**Pull request merged**
