### PR TITLE
Closes #406

### LINKED ISSUE #406: [bug] Clans can rival themselves, meaning crew kills get them extra points
Simple as it sounds crews can rival themselvs, they should not be able to do this, this means they can clock up a larger kill count.

### PR DESCRIPTION
**Pull request by RoinujNosde**
I have used getTag and equals to compare clans because I was not sure if equals would work directly at the clans. Would it?

### CODE REVIEW

**Comment by marcelo-mason** [comment]
Awesome

**Comment by marcelo-mason** [comment]
Yep it would:  https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L79

**Comment by RoinujNosde** [comment]
Nice.
Next time will use it.

**Comment by marcelo-mason** [comment]
Thank you for these btw, pretty sure others appreciate them as well.  Next time you make an edit, also up the version number on the pom.xml so ppls know to download a new version (2.7.1, then 2.7.2, etc.):

https://github.com/marcelo-mason/SimpleClans/blob/master/pom.xml#L5

**Comment by RoinujNosde** [comment]
Beleza! ;)

**Pull request merged**
