### PR TITLE
Closes #336

### LINKED ISSUE #336: Toggling bank deposit/withdraw does not give visual response
When using `/clan toggle deposit` no message is shown, making it impossible to figure out whether the deposit has actually been toggled ON or OFF, seeing there is no command to retrieve this "status".

This applies to both deposit and withdraw. A leader performing the toggle does not have the ability to check whether his clan members can actually or not deposit or withdraw until they get one to test a dummy deposit/withdrawal for them.

Fixing this should be just a one liner in the code and two new language messages, for both withdraw and deposit toggle commands.

### PR DESCRIPTION
**Pull request by RoinujNosde**

### CODE REVIEW

**Comment by marcelo-mason** [comment]
Looks good.  Thanks!

2 Tips:

1. Group all the changes for a specific fix in a single commit, instead of individually, and give it a commit message that describes what you are fixing.  For example, this one would be better as:

*  Added visual response to bank actions (Closes #336)

instead of 

* New message
* New message
* Change version

Also note:  adding the "(Closes #XXX)" text on the commit message itself triggers github to close the issue automatically ;)

2. When you merge, choose "Rebase and merge" from the dropdown.

**Comment by RoinujNosde** [comment]
> Group all the changes for a specific fix or feature in a single commit, rather than individually, and give it a commit message that describes the whole thing.

I am not home, so I make this changes on mobile.

> Also note: adding the "(Closes #XXX)" text on the commit message itself triggers github to close the issue automatically when you commit it ;)

I know. ;)

> Leave the merging of the pull requests to me. That allows me review the code, or update the commit message before it goes on the main branch.

OK.

**Comment by marcelo-mason** [comment]
Thanks!  I did the squashing btw already.  "git pull" when you get home to get latest changes.

**Comment by RoinujNosde** [comment]
All right.

**Comment by marcelo-mason** [comment]
Thanks again for your help!

**Comment by RoinujNosde** [comment]
No problem, I like this plugin.

**Pull request merged**
