### PR TITLE
Improved KDR command

### PR DESCRIPTION
**Pull request by RoinujNosde**
* Permission for colors in tags
* Players can reset their KDR now (or not, if disabled in the config) if they have the permission and the money (or not, if, also, disabled)
* Admins can now reset just one player's kdr
* Added missing language for the resetkdr command

### CODE REVIEW

**Comment by marcelo-mason** [comment]
Very nice

**Comment by RoinujNosde** [comment]
Thanks

**Comment by ArtNRG** [comment]
The build with this pull request is failed. Error: method purchaseHomeRegroup(Player) is already defined in class ClanManager
http://104.236.246.108:8080/job/SimpleClans/67/console

**Comment by RoinujNosde** [comment]
@ArtNRG Thanks for the feedback.

**Comment by ArtNRG** [comment]
@RoinujNosde it will be great to be able to reset KDR to the offline player.

**Comment by RoinujNosde** [comment]
@ArtNRG #478

**Pull request merged**
